#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# 确保脚本抛出遇到的错误
set -e
# 生成静态文件

npm run build


# 进入生成的文件夹
cd "./docs/.vuepress/dist"

git init
git add .
git commit --no-verify -m 'deploy'

# 如果发布到 origin gh-pages
git branch -m master gh-pages # 匹配路径
git remote add origin "https://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@github.com/Da222Da/Da222Da.github.io.git"
git push -f -u origin gh-pages

rm -rf "./docs/.vuepress/dist"
cd -